use anyhow::{bail, Result};

#[derive(Clone, Copy, PartialEq)]
pub enum Opcode {
  Nop,
  InitStack,
  Call,
  SysCall,
  Ret,
  Retv,
  Jmp,
  Jz,
  PushNil,
  PushTrue,
  PushIntI32,
  PushIntI16,
  PushIntI8,
  PushFloat,
  PushString,
  PushGlbvar,
  PushStkvar,
  PushGlbvarTable,
  PushStkvarTable,
  PushTop,
  PushReturn,
  PopGlbvar,
  PopStkvar,
  PopGlbvarTable,
  PopStkvarTable,
  Neg,
  Add,
  Sub,
  Mul,
  Div,
  Mod,
  BitTest,
  And,
  Or,
  SetE,
  SetNe,
  SetG,
  SetGe,
  SetL,
  SetLe,
}

pub enum IntEncoding {
  I8,
  I16,
  I32,
}

pub enum Operand {
  None,
  InitStack { arg_count: u8, local_count: u8 },
  Label(String),
  Address(u32),
  SyscallName(String),
  String(Vec<u8>),
  Int(i32, IntEncoding),
  Float(f32),
  U16(u16),
  I8(i8),
}

pub struct ParsedInstruction {
  pub opcode: Opcode,
  pub operand: Operand,
}

pub fn decode_opcode(byte: u8) -> Result<Opcode> {
  match byte {
    0x00 => Ok(Opcode::Nop),
    0x01 => Ok(Opcode::InitStack),
    0x02 => Ok(Opcode::Call),
    0x03 => Ok(Opcode::SysCall),
    0x04 => Ok(Opcode::Ret),
    0x05 => Ok(Opcode::Retv),
    0x06 => Ok(Opcode::Jmp),
    0x07 => Ok(Opcode::Jz),
    0x08 => Ok(Opcode::PushNil),
    0x09 => Ok(Opcode::PushTrue),
    0x0A => Ok(Opcode::PushIntI32),
    0x0B => Ok(Opcode::PushIntI16),
    0x0C => Ok(Opcode::PushIntI8),
    0x0D => Ok(Opcode::PushFloat),
    0x0E => Ok(Opcode::PushString),
    0x0F => Ok(Opcode::PushGlbvar),
    0x10 => Ok(Opcode::PushStkvar),
    0x11 => Ok(Opcode::PushGlbvarTable),
    0x12 => Ok(Opcode::PushStkvarTable),
    0x13 => Ok(Opcode::PushTop),
    0x14 => Ok(Opcode::PushReturn),
    0x15 => Ok(Opcode::PopGlbvar),
    0x16 => Ok(Opcode::PopStkvar),
    0x17 => Ok(Opcode::PopGlbvarTable),
    0x18 => Ok(Opcode::PopStkvarTable),
    0x19 => Ok(Opcode::Neg),
    0x1A => Ok(Opcode::Add),
    0x1B => Ok(Opcode::Sub),
    0x1C => Ok(Opcode::Mul),
    0x1D => Ok(Opcode::Div),
    0x1E => Ok(Opcode::Mod),
    0x1F => Ok(Opcode::BitTest),
    0x20 => Ok(Opcode::And),
    0x21 => Ok(Opcode::Or),
    0x22 => Ok(Opcode::SetE),
    0x23 => Ok(Opcode::SetNe),
    0x24 => Ok(Opcode::SetG),
    0x25 => Ok(Opcode::SetGe),
    0x26 => Ok(Opcode::SetL),
    0x27 => Ok(Opcode::SetLe),
    _ => bail!("unknown opcode 0x{:02X}", byte),
  }
}

pub fn encode_opcode(op: Opcode) -> u8 {
  match op {
    Opcode::Nop => 0x00,
    Opcode::InitStack => 0x01,
    Opcode::Call => 0x02,
    Opcode::SysCall => 0x03,
    Opcode::Ret => 0x04,
    Opcode::Retv => 0x05,
    Opcode::Jmp => 0x06,
    Opcode::Jz => 0x07,
    Opcode::PushNil => 0x08,
    Opcode::PushTrue => 0x09,
    Opcode::PushIntI32 => 0x0A,
    Opcode::PushIntI16 => 0x0B,
    Opcode::PushIntI8 => 0x0C,
    Opcode::PushFloat => 0x0D,
    Opcode::PushString => 0x0E,
    Opcode::PushGlbvar => 0x0F,
    Opcode::PushStkvar => 0x10,
    Opcode::PushGlbvarTable => 0x11,
    Opcode::PushStkvarTable => 0x12,
    Opcode::PushTop => 0x13,
    Opcode::PushReturn => 0x14,
    Opcode::PopGlbvar => 0x15,
    Opcode::PopStkvar => 0x16,
    Opcode::PopGlbvarTable => 0x17,
    Opcode::PopStkvarTable => 0x18,
    Opcode::Neg => 0x19,
    Opcode::Add => 0x1A,
    Opcode::Sub => 0x1B,
    Opcode::Mul => 0x1C,
    Opcode::Div => 0x1D,
    Opcode::Mod => 0x1E,
    Opcode::BitTest => 0x1F,
    Opcode::And => 0x20,
    Opcode::Or => 0x21,
    Opcode::SetE => 0x22,
    Opcode::SetNe => 0x23,
    Opcode::SetG => 0x24,
    Opcode::SetGe => 0x25,
    Opcode::SetL => 0x26,
    Opcode::SetLe => 0x27,
  }
}

pub fn mnemonic_to_opcode(m: &str) -> Option<Opcode> {
  match m {
    "nop" => Some(Opcode::Nop),
    "init_stack" => Some(Opcode::InitStack),
    "call" => Some(Opcode::Call),
    "syscall" => Some(Opcode::SysCall),
    "ret" => Some(Opcode::Ret),
    "retv" => Some(Opcode::Retv),
    "jmp" => Some(Opcode::Jmp),
    "jz" => Some(Opcode::Jz),
    "push_nil" => Some(Opcode::PushNil),
    "push_true" => Some(Opcode::PushTrue),
    "push_int" => Some(Opcode::PushIntI32),
    "push_float" => Some(Opcode::PushFloat),
    "push_string" => Some(Opcode::PushString),
    "push_glbvar" => Some(Opcode::PushGlbvar),
    "push_stkvar" => Some(Opcode::PushStkvar),
    "push_glbvar_table" => Some(Opcode::PushGlbvarTable),
    "push_stkvar_table" => Some(Opcode::PushStkvarTable),
    "push_top" => Some(Opcode::PushTop),
    "push_return" => Some(Opcode::PushReturn),
    "pop_glbvar" => Some(Opcode::PopGlbvar),
    "pop_stkvar" => Some(Opcode::PopStkvar),
    "pop_glbvar_table" => Some(Opcode::PopGlbvarTable),
    "pop_stkvar_table" => Some(Opcode::PopStkvarTable),
    "neg" => Some(Opcode::Neg),
    "add" => Some(Opcode::Add),
    "sub" => Some(Opcode::Sub),
    "mul" => Some(Opcode::Mul),
    "div" => Some(Opcode::Div),
    "mod" => Some(Opcode::Mod),
    "bit_test" => Some(Opcode::BitTest),
    "and" => Some(Opcode::And),
    "or" => Some(Opcode::Or),
    "set_e" => Some(Opcode::SetE),
    "set_ne" => Some(Opcode::SetNe),
    "set_g" => Some(Opcode::SetG),
    "set_ge" => Some(Opcode::SetGe),
    "set_l" => Some(Opcode::SetL),
    "set_le" => Some(Opcode::SetLe),
    _ => None,
  }
}

pub fn opcode_mnemonic(op: Opcode) -> &'static str {
  match op {
    Opcode::Nop => "nop",
    Opcode::InitStack => "init_stack",
    Opcode::Call => "call",
    Opcode::SysCall => "syscall",
    Opcode::Ret => "ret",
    Opcode::Retv => "retv",
    Opcode::Jmp => "jmp",
    Opcode::Jz => "jz",
    Opcode::PushNil => "push_nil",
    Opcode::PushTrue => "push_true",
    Opcode::PushIntI32 | Opcode::PushIntI16 | Opcode::PushIntI8 => "push_int",
    Opcode::PushFloat => "push_float",
    Opcode::PushString => "push_string",
    Opcode::PushGlbvar => "push_glbvar",
    Opcode::PushStkvar => "push_stkvar",
    Opcode::PushGlbvarTable => "push_glbvar_table",
    Opcode::PushStkvarTable => "push_stkvar_table",
    Opcode::PushTop => "push_top",
    Opcode::PushReturn => "push_return",
    Opcode::PopGlbvar => "pop_glbvar",
    Opcode::PopStkvar => "pop_stkvar",
    Opcode::PopGlbvarTable => "pop_glbvar_table",
    Opcode::PopStkvarTable => "pop_stkvar_table",
    Opcode::Neg => "neg",
    Opcode::Add => "add",
    Opcode::Sub => "sub",
    Opcode::Mul => "mul",
    Opcode::Div => "div",
    Opcode::Mod => "mod",
    Opcode::BitTest => "bit_test",
    Opcode::And => "and",
    Opcode::Or => "or",
    Opcode::SetE => "set_e",
    Opcode::SetNe => "set_ne",
    Opcode::SetG => "set_g",
    Opcode::SetGe => "set_ge",
    Opcode::SetL => "set_l",
    Opcode::SetLe => "set_le",
  }
}

pub fn opcode_size(op: Opcode) -> u32 {
  match op {
    Opcode::InitStack => 3,
    Opcode::Call | Opcode::Jmp | Opcode::Jz => 5,
    Opcode::SysCall => 3,
    Opcode::PushIntI32 | Opcode::PushFloat => 5,
    Opcode::PushIntI16 => 3,
    Opcode::PushIntI8 | Opcode::PushString => 2,
    Opcode::PushGlbvar | Opcode::PushGlbvarTable | Opcode::PopGlbvar | Opcode::PopGlbvarTable => 3,
    Opcode::PushStkvar | Opcode::PushStkvarTable | Opcode::PopStkvar | Opcode::PopStkvarTable => 2,
    _ => 1,
  }
}
